name: Backend CI

on:
  pull_request:
    branch:
      - main
  # TODO - remove push trigger
  push:
    branch:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lint
      - run: |
          pip install --user pipenv
          python -m pipenv install
          python -m pipenv run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run test
      - run: |
          pip install --user pipenv
          python -m pipenv install
          python -m pipenv run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run test
      - run: docker build --tag mp-backend:$GITHUB_SHA .