name: Backend CI

on:
  pull_request:
    branch:
      - main
  # TODO - remove push trigger
  push:
    branch:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pipenv
        run: pip install --user pipenv
      - name: pipenv install
        run: cd starter/frontend && python -m pipenv install
      - name: run lint 
        run: python -m pipenv run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        run: |
          cd starter/frontend
          pip install --user pipenv
          python -m pipenv install
          python -m pipenv run test
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        run: |
          cd starter/frontend
          docker build --tag mp-backend:$GITHUB_SHA .