name: Frontend CI

on:
  pull_requests:
    branch:
      - main
  # TODO - remove push trigger
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello from Octo Organization
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello from Octo Organization
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Run a one-line script
        run: echo Hello from Octo Organization
