name: frontend_ci
on: [workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: lint
    run: echo "hello world - lint"
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
    run: echo "hello world - test"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build
    run: echo "hello world - build"
