name: Frontend CI

on:
  pull_request:
    branch:
      - main
  # TODO - remove push trigger
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cd starter/frontend && npm install
      - name: Run lint
        run: cd starter/frontend && npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cd starter/frontend && npm install
      - name: Run Test
        run: cd starter/frontend && npm run test
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Install dependencies
        run: cd starter/frontend && npm install
      - name: Build in Docker
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
