name: Frontend CI

on:
  pull_request:
    branch:
      - main
  # TODO - remove push trigger
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        run: npm run lint
      - name: Perform a cache action to restore cache before dependency install
        run: npm run lint
      - name: Install dependencies
        run: cd starter/frontend && npm install
      - name: Run lint
        run: npm run lint
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello from Octo Organization
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Run a one-line script
        run: echo Hello from Octo Organization
