name: Frontend CD

on:
  push:
    branch:
      - main
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cd starter/frontend && npm install
      - name: Run lint
        run: cd starter/frontend && npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cd starter/frontend && npm install
      - name: Run Test
        run: cd starter/frontend && npm run test
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: cd starter/frontend && npm install
      - name: Build in Docker
        run: |
          cd starter/frontend
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:$GITHUB_SHA .
      - name: Push to ECR 
        run: |
          cd starter/frontend
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com
          docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/mp-frontend
      - name: Deploy app using kubectl to an EKS cluster
        run: exit 1
